name: play_lab
description: A new Flutter project.
publish_to: 'none'

#Platform  Firebase App Id
#Android   1:478780527317:android:354bc924f271095fa3485c
#IOS       1:478780527317:ios:a4dd9a516223ecd9a3485c

version: 1.0.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:  
  flutter:
    sdk: flutter
  google_sign_in: 6.3.0
  cached_network_image: ^3.3.1
  readmore: ^2.2.0
  get: ^4.6.6
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  carousel_slider: 5.0.0
  shared_preferences: 2.5.3
  flutter_rating_bar: ^4.0.1
  country_picker: ^2.0.25
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  # flutter_widget_from_html: 0.16.0
  # flutter_inappwebview: 6.1.5
  chewie: ^1.7.5
  video_player: ^2.8.3
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  path_provider: ^2.0.14
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: 18.0.1
  firebase_messaging: 15.2.1
  firebase_analytics: 11.4.1
  firebase_core: 3.10.1
  firebase_core_platform_interface: ^5.0.0 
  awesome_dialog: ^3.0.2
  permission_handler: ^11.3.0
  firebase_auth: 5.4.1
  url_launcher: ^6.2.5
  # flutter_facebook_auth: 7.1.1
  # google_mobile_ads: 5.3.1
  pay: ^2.0.0
  flutter_cache_manager: ^3.3.1
  cool_dropdown: ^2.1.0
  pusher_channels_flutter: 2.5.0
  flutter_animate: ^4.5.0
  html: ^0.15.4
  file_picker: 10.0.0
  image_picker: 1.1.2
  in_app_purchase: ^3.1.13
  dio: ^5.4.3+1
  another_flushbar: ^1.12.30
  in_app_purchase_storekit: any
  keep_screen_on: 4.0.0
  flutter_exit_app: 1.1.4
  open_file: 3.5.10
  zoom_tap_animation: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  win32: ^5.10.0
  archive: ^4.0.2
  qr_flutter: ^4.1.0
  # webview_flutter_plus: ^0.4.15
  webview_flutter: 4.11.0
  # webview_flutter_android: 4.3.2
  # wakelock: ^0.4.0
dependency_overrides:
  intl: any
  http: any
  flutter_plugin_android_lifecycle: 2.0.27
  image_picker_android: 0.8.12+22
  in_app_purchase_android: 0.4.0+1
  path_provider_android: 2.2.16
  permission_handler_android: 13.0.1
  url_launcher_android: 6.3.15
  video_player_android: 2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/social/
    - assets/animation/
    - assets/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700

